/*
 * ToradexOakG3AxisAccelerationSensorGUI.java
 *
 * Created on April 22, 2008, 3:21 PM
 */
package ch.unizh.ini.caviar.hardwareinterface.usb.toradex;

import ch.unizh.ini.caviar.hardwareinterface.HardwareInterfaceException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.plaf.DimensionUIResource;

/**
 * Tests the acceleration sensor
 * @author  tobi
 */
public class ToradexOakG3AxisAccelerationSensorGUI extends javax.swing.JFrame {

    static ToradexOakG3AxisAccelerationSensor sensor;
    JPanel panel;
    private boolean stop = false;
       PlotPanel plotPanel ;
       
    /** Creates new form ToradexOakG3AxisAccelerationSensorGUI */
    public ToradexOakG3AxisAccelerationSensorGUI() {
        setPreferredSize(new Dimension(400, 400));
        initComponents();
         plotPanel = new PlotPanel();
        plotPanel.setPreferredSize(new Dimension(400, 400));
        getContentPane().add(plotPanel, java.awt.BorderLayout.CENTER);
        pack();
    }

    class PlotPanel extends JPanel {

        @Override
        public void paint(Graphics g) {
            super.paint(g);
            if (sensor == null) {
                return;
            }
            Graphics2D g2 = (Graphics2D) g;
            g2.setColor(Color.RED);
            g2.drawOval((int) (getWidth() * sensor.getAccel()[0] / sensor.MAX_ACCEL),
                    (int) (getHeight() * sensor.getAccel()[1] / sensor.MAX_ACCEL),
                    4, 4);
        }
    }        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceleration");

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        ToradexOakG3AxisAccelerationSensorGUI frame = new ToradexOakG3AxisAccelerationSensorGUI();
        frame.setVisible(true);
try {
            sensor = new ToradexOakG3AxisAccelerationSensor();
            sensor.open();
            while(true){
                frame.plotPanel.repaint(100);
                System.out.println("called repaint");
                try{Thread.currentThread().sleep(100);}catch(InterruptedException e){}
            }
        } catch (HardwareInterfaceException ex) {
            Logger.getLogger(ToradexOakG3AxisAccelerationSensorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
