/*

 * Created on September 15, 2002, 8:08 PM

 */
package net.sf.jaer.graphics;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.net.URI;
import java.util.List;
import java.util.logging.Logger;

import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import net.sf.jaer.JaerConstants;
import net.sf.jaer.JaerUpdaterFrame;

/**
 * The About dialog. Version and git commit come from
 * {@link net.sf.jaer.JaerConstants#getBuildVersion()} ({@code BUILDVERSION.txt}
 * written by Ant).
 *
 * @author tobi
 */
public class AEViewerAboutDialog extends javax.swing.JDialog {

    public final static String VERSION_FILE = "BUILDVERSION.txt";
    static Logger log = Logger.getLogger("net.sf.jaer");
    AEViewer parent=null;

    /**
     * Creates new form AEViewerAboutDialog
     */
    public AEViewerAboutDialog(AEViewer parent, boolean modal) {
        super(parent, modal);
        this.parent=parent;
        initComponents();
        setTitle(JaerConstants.APPLICATION_NAME);
        aboutLabel.setText("<html><center><h1>" + JaerConstants.APPLICATION_NAME + "</h1></center></html>");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource(JaerConstants.ICON_IMAGE)).getImage());
        fillIdentityTable();
        pack();
        setSize(Math.max(getWidth(), 720), Math.max(getHeight(), 480));
        setLocationRelativeTo(parent);
    }

    private void fillIdentityTable() {
        List<String[]> rows = JaerConstants.getBuildIdentityRows();
        DefaultTableModel model = new DefaultTableModel(new Object[] { "Field", "Value" }, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        for (String[] row : rows) {
            model.addRow(row);
        }
        identityTable.setModel(model);
        identityTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        identityTable.setRowHeight(22);
        identityTable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        identityTable.setCellSelectionEnabled(true);
        identityTable.getTableHeader().setReorderingAllowed(false);
        identityTable.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 13));
        identityTable.getTableHeader().setFont(new Font(Font.SANS_SERIF, Font.BOLD, 13));
        TableColumn fieldCol = identityTable.getColumnModel().getColumn(0);
        fieldCol.setPreferredWidth(120);
        fieldCol.setMaxWidth(160);
        identityTable.getColumnModel().getColumn(1).setPreferredWidth(520);
        identityTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                setToolTipText(value == null ? null : value.toString());
                return c;
            }
        });
    }

    private void copyIdentityTable() {
        String tsv = JaerConstants.getBuildIdentityTable();
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(new StringSelection(tsv), null);
        log.info("Copied build identity table to clipboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        jaerProjectLinkLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        identityTable = new javax.swing.JTable();
        updatesButton = new javax.swing.JButton();
        copyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        aboutLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aboutLabel.setText("<html> <center> <h1> jAER - Desktop Application for Event Sensors </h1> </center></html>");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jaerProjectLinkLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jaerProjectLinkLabel.setText("<html> <em><a href=\"http://jaerproject.org\">jaerproject.org</a> </em></html>");
        jaerProjectLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jaerProjectLinkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jaerProjectLinkLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jaerProjectLinkLabelMouseExited(evt);
            }
        });

        identityTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(identityTable);

        updatesButton.setText("Check for updates...");
        updatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatesButtonActionPerformed(evt);
            }
        });

        copyButton.setText("Copy");
        copyButton.setToolTipText("Copy Field / Value table as tab-separated text");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(77, 77, 77)
                        .add(jaerProjectLinkLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(56, 56, 56)
                        .add(copyButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(updatesButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                        .add(okButton))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, aboutLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(aboutLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(jaerProjectLinkLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(copyButton)
                    .add(updatesButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
            dispose();
            // Add your handling code here:
	}//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
            setVisible(false);
            dispose();
	}//GEN-LAST:event_closeDialog

	private void jaerProjectLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaerProjectLinkLabelMouseClicked
            try {
                showInBrowser(JaerConstants.HELP_URL_JAER_HOME);

                setCursor(Cursor.getDefaultCursor());
            } catch (Exception e) {
                log.warning(e.toString());
            }

	}//GEN-LAST:event_jaerProjectLinkLabelMouseClicked

    private void showInBrowser(String url) {
        if (!Desktop.isDesktopSupported()) {
            log.warning("No Desktop support, can't show help from " + url);
            return;
        }
        try {
            Desktop.getDesktop().browse(new URI(url));
        } catch (Exception ex) {
            log.warning("Couldn't show " + url + "; caught " + ex);
        }
    }

	private void jaerProjectLinkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaerProjectLinkLabelMouseEntered
            setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
	}//GEN-LAST:event_jaerProjectLinkLabelMouseEntered

	private void jaerProjectLinkLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jaerProjectLinkLabelMouseExited
            setCursor(Cursor.getDefaultCursor());
	}//GEN-LAST:event_jaerProjectLinkLabelMouseExited

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        copyIdentityTable();
    }

    private void updatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatesButtonActionPerformed
        dispose();
        if(parent.getJaerUpdaterFrame()==null){
            parent.setJaerUpdaterFrame(new JaerUpdaterFrame());
        }
        parent.getJaerUpdaterFrame().setVisible(true);
        parent.getJaerUpdaterFrame().setLocationRelativeTo(parent);
    }//GEN-LAST:event_updatesButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JButton copyButton;
    private javax.swing.JTable identityTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jaerProjectLinkLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton updatesButton;
    // End of variables declaration//GEN-END:variables

}
