/*
 * ToradexOakG3AxisAccelerationSensorGUI.java
 *
 * Created on April 22, 2008, 3:21 PM
 */
package net.sf.jaer.hardwareinterface.usb.toradex;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JPanel;

import net.sf.jaer.hardwareinterface.HardwareInterfaceException;

/**
 * Tests the acceleration sensor
 * @author  tobi
 */
public class ToradexOakG3AxisAccelerationSensorGUI extends JFrame implements PropertyChangeListener {

    static Logger log = Logger.getLogger("ToradexOakG3AxisAccelerationSensor");
    JPanel panel;
    private boolean stop = false;
    PlotPanel plotPanel;
    ToradexOakG3AxisAccelerationSensor sensor;
    float xmax = Float.NEGATIVE_INFINITY, ymax = Float.NEGATIVE_INFINITY, zmax = Float.NEGATIVE_INFINITY;

    /** Creates new form ToradexOakG3AxisAccelerationSensorGUI */
    public ToradexOakG3AxisAccelerationSensorGUI(ToradexOakG3AxisAccelerationSensor sensor) {
        this.sensor = sensor;
        setPreferredSize(new Dimension(400, 400));
        initComponents();
        plotPanel = new PlotPanel();
        plotPanel.setPreferredSize(new Dimension(400, 400));
        graphicsPanel.add(plotPanel, java.awt.BorderLayout.CENTER);
        pack();
        try {
            sensor.open();
            sensor.getSupport().addPropertyChangeListener(this);
        } catch (HardwareInterfaceException e) {
            e.printStackTrace();
        }
    }

    class PlotPanel extends JPanel {

        @Override
        public void paint(Graphics g) {
            super.paint(g);
            if (sensor == null) {
                return;
            }
            Graphics2D g2 = (Graphics2D) g;
            g2.setBackground(Color.WHITE);
            g2.clearRect(0, 0, getWidth(), getHeight());
            g2.setColor(Color.RED);
            g2.setStroke(new BasicStroke(2f));
            ToradexOakG3AxisAccelerationSensor.Acceleration v=sensor.getAcceleration();
            int w=getWidth(), h=getHeight();
            final float m = ToradexOakG3AxisAccelerationSensor.MAX_ACCEL;
            float x = w*v.x/m+w/2;
            float y = h*v.y/m+h/2;
            float z = (v.z+m/2)/m*h/10;
            final int r = (int)z;
            int xx=(int)(x-r), yy=(int)(y-r);
            g2.drawOval(xx, yy, r * 2, r * 2);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        graphicsPanel = new javax.swing.JPanel();
        textPanel = new javax.swing.JPanel();
        xField = new javax.swing.JTextField();
        yField = new javax.swing.JTextField();
        zField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acceleration");

        graphicsPanel.setLayout(new java.awt.BorderLayout());

        xField.setColumns(10);
        xField.setFont(new java.awt.Font("Courier New", 0, 18));
        xField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        yField.setColumns(10);
        yField.setFont(new java.awt.Font("Courier New", 0, 18));
        yField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        zField.setColumns(10);
        zField.setFont(new java.awt.Font("Courier New", 0, 18));
        zField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        javax.swing.GroupLayout textPanelLayout = new javax.swing.GroupLayout(textPanel);
        textPanel.setLayout(textPanelLayout);
        textPanelLayout.setHorizontalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createSequentialGroup()
                .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        textPanelLayout.setVerticalGroup(
            textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(zField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(textPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(graphicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graphicsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        ToradexOakG3AxisAccelerationSensorGUI frame = new ToradexOakG3AxisAccelerationSensorGUI(new ToradexOakG3AxisAccelerationSensor());
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphicsPanel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel textPanel;
    private javax.swing.JTextField xField;
    private javax.swing.JTextField yField;
    private javax.swing.JTextField zField;
    // End of variables declaration//GEN-END:variables
    public void propertyChange(PropertyChangeEvent evt) {
        ToradexOakG3AxisAccelerationSensor.Acceleration a= sensor.getAcceleration();
        xField.setText(String.format("%.3f", a.x));
        yField.setText(String.format("%.3f", a.y));
        zField.setText(String.format("%.3f", a.z));
        plotPanel.repaint();
    }
}
