/*
 * OpticalFlowIntegratorControlPanel.java
 *
 * Created on Nov 18, 2011, 1:56:02 PM
 */
package ch.unizh.ini.jaer.projects.opticalflow;

import java.util.logging.Logger;

/**
 * simple GUI controlling <code>OpticalFlowIntegrator</code>
 * 
 * @see OpticalFlowIntegrator
 * @author andstein
 */
public class OpticalFlowIntegratorControlPanel extends javax.swing.JPanel {
    static final Logger log=Logger.getLogger(OpticalFlowIntegratorControlPanel.class.getName());

    OpticalFlowIntegrator integrator;
    /** Creates new form OpticalFlowIntegratorControlPanel */
    public OpticalFlowIntegratorControlPanel(OpticalFlowIntegrator integrator) {
        initComponents();
        
        this.integrator= integrator;
        updateGui();
    }
    
    protected void updateGui() {
        tracesCB.setSelected( integrator.isShowTraces());
        medianCB.setSelected( integrator.isUsingFilter());
        optionCB.setSelected( integrator.isDebugOption());
        param1.setText( integrator.getDebugParam1() );
        param2.setText( integrator.getDebugParam2() );
    }
    
    protected void updateIntegrator() {
        integrator.doShowTraces( tracesCB.isSelected() );
        integrator.setUseFilter( medianCB.isSelected() );
        integrator.setDebugOption( optionCB.isSelected() );
        integrator.setDebugParam1( param1.getText() );
        integrator.setDebugParam2( param2.getText() );
        log.info("updated GUI->OFI");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tracesCB = new javax.swing.JCheckBox();
        medianCB = new javax.swing.JCheckBox();
        optionCB = new javax.swing.JCheckBox();
        param1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        param2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        tracesCB.setText("traces");
        tracesCB.setToolTipText("whether or not to display graph traces");
        tracesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracesCBActionPerformed(evt);
            }
        });

        medianCB.setText("median filter");
        medianCB.setToolTipText("enables the median filter to smooth raw global flow output");
        medianCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianCBActionPerformed(evt);
            }
        });

        optionCB.setText("option");
        optionCB.setToolTipText("debug option; see source code");
        optionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionCBActionPerformed(evt);
            }
        });

        param1.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        param1.setToolTipText("debug parameter; see source code");
        param1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param1ActionPerformed(evt);
            }
        });

        jLabel1.setText("parameter1");

        param2.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        param2.setToolTipText("debug parameter; see source code");
        param2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                param2ActionPerformed(evt);
            }
        });

        jLabel2.setText("parameter2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tracesCB)
                    .addComponent(medianCB)
                    .addComponent(optionCB)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tracesCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medianCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(param1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(param2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tracesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracesCBActionPerformed
        updateIntegrator();
    }//GEN-LAST:event_tracesCBActionPerformed

    private void medianCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medianCBActionPerformed
        updateIntegrator();
    }//GEN-LAST:event_medianCBActionPerformed

    private void optionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionCBActionPerformed
        updateIntegrator();
    }//GEN-LAST:event_optionCBActionPerformed

    private void param1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param1ActionPerformed
        updateIntegrator();
    }//GEN-LAST:event_param1ActionPerformed

    private void param2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_param2ActionPerformed
        updateIntegrator();
    }//GEN-LAST:event_param2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox medianCB;
    private javax.swing.JCheckBox optionCB;
    private javax.swing.JTextField param1;
    private javax.swing.JTextField param2;
    private javax.swing.JCheckBox tracesCB;
    // End of variables declaration//GEN-END:variables
}
