/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320 */

#ifndef _Included_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
#define _Included_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_MAX_BYTES_PER_BIAS
#define ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_MAX_BYTES_PER_BIAS 4L
/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeGetAddresses
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeGetAddresses
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeGetTimestamps
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeGetTimestamps
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeOverrunOccured
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeOverrunOccured
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeOpen__
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeAcquireAvailableEventsFromDriver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeAcquireAvailableEventsFromDriver
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeGetNumEventsAcquired
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeGetNumEventsAcquired
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeSetEventAcquisitionEnabled
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeSetEventAcquisitionEnabled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeGetNumDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeGetNumDevices
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeOpen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeOpen__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeSetPowerdown
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeSetPowerdown
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeSendBiases
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeSendBiases
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeFlashBiases
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeFlashBiases
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeResetTimestamps
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeResetTimestamps
  (JNIEnv *, jobject);

/*
 * Class:     ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320
 * Method:    nativeSetServo
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_ch_unizh_ini_caviar_hardwareinterface_usb_SiLabsC8051F320_nativeSetServo
  (JNIEnv *, jobject, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
