/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DVSActivityMonitor.java
 *
 * Created on Jan 29, 2009, 10:52:40 AM
 */
package ch.unizh.ini.jaer.projects.holger;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.util.logging.Logger;
import javax.swing.JApplet;
import javax.swing.JFrame;
import javax.swing.border.TitledBorder;
import net.sf.jaer.util.chart.Axis;
import net.sf.jaer.util.chart.Category;
import net.sf.jaer.util.chart.Series;
import net.sf.jaer.util.chart.XYChart;

/**
 * Shows a stream of AE events from a retina and plots the recent activitySeries over msTime as a rolling chart.
 * Used in the INI foyer to show kitchen activitySeries.
 * @author tobi
 */
public class BinsApplet extends javax.swing.JApplet {
    private Logger log = Logger.getLogger("JAERAppletViewer");
    public Bins myBins;

    volatile boolean stopflag = false;
    private long frameDelayMs = 500;
    // activity
    private final int NUM_ACTIVITY_SAMPLES = 10000;
    private final int ACTVITY_SECONDS_TO_SHOW = 300;
    public Series activitySeries;
    private Axis binAxis;
    private Axis activityAxis;
    private Category activityCategory;
    private XYChart activityChart;
    private float maxActivity = 0;

    @Override
    public String getAppletInfo() {
        return "ITDApplet";
    }

    public void updateBins(Bins newBins) {
        myBins=newBins;
    }

    /** Initializes the applet */
    @Override
    public void init() {
        try {
            log.info("applet init");
            initComponents();

            activitySeries = new Series(2, NUM_ACTIVITY_SAMPLES);

            binAxis = new Axis(0, ACTVITY_SECONDS_TO_SHOW);
            binAxis.setTitle("bins");
            binAxis.setUnit("#bin");

            activityAxis = new Axis(0, 1); // will be normalized
            activityAxis.setTitle("activity");

            activityCategory = new Category(activitySeries, new Axis[]{binAxis, activityAxis});
            activityCategory.setColor(new float[]{0.0f, 0.0f, 1.0f});

            activityChart = new XYChart("");
            activityChart.setBackground(Color.black);
            activityChart.setForeground(Color.white);
            activityChart.setGridEnabled(false);
            activityChart.addCategory(activityCategory);

            activityPanel.add(activityChart, BorderLayout.CENTER);
            ((TitledBorder) activityPanel.getBorder()).setTitle("activity in bins");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    @Override
    synchronized public void start() {
        super.start();
        stopflag = false;
        log.info("applet starting");
        repaint();  // starts recursive repaint, finishes when paint returns without calling repaint itself
    }

    @Override
    synchronized public void stop() {
        super.stop();
        log.info("applet stop, setting stopflag=true");
        stopflag = true;
    }

    @Override
    synchronized public void paint(Graphics g) {
        super.paint(g);
        if (stopflag) {
            log.info("stop is set, not painting again or calling repaint");
            return;
        }
        try {
            if (myBins != null)
            {
                maxActivity=0;
                activitySeries.clear();
                //log.info("numbins="+myBins.numOfBins);
                for (int i = 0; i<myBins.numOfBins; i++ )
                {
                        if (maxActivity < myBins.bins[i])
                            maxActivity = myBins.bins[i];
                        activitySeries.add(i,myBins.bins[i]);
                }
                activitySeries.add(myBins.numOfBins,0);

                binAxis.setMaximum(myBins.numOfBins);
                binAxis.setMinimum(0);
                activityAxis.setMaximum(maxActivity);
                activityChart.display();
            }
            else
            {
                log.warning("myBins=null");
            }
        } catch (Exception e) {
            log.warning("while displaying activity chart caught " + e);
        }

        try {
            repaint(frameDelayMs); // recurse
        } catch (Exception e) {
            log.warning("while repainting, caught exception " + e);
            e.printStackTrace();
        }
    }

    /**
     * For testing in JFrame
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JApplet applet = new BinsApplet();
        JFrame frame = new ITDJFrame(applet);
        applet.init();
        applet.start();
        frame.setVisible(true);
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activityPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));

        activityPanel.setBackground(new java.awt.Color(0, 0, 0));
        activityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recent activity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        activityPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(activityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );

        activityPanel.getAccessibleContext().setAccessibleName("Bins");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activityPanel;
    // End of variables declaration//GEN-END:variables
}
