/*
 * TopologyTrackerControl.java
 *
 * Created on November 25, 2008, 11:17 PM
 */

package ch.unizh.ini.jaer.projects.topology;


/**
 * A large-button control for the TopologyTrackerDemo.
 * @author  tobi
 */
public class TopologyTrackerControl extends javax.swing.JFrame {
    TopologyTracker filter;
    /** Creates new form TopologyTrackerControl */
    public TopologyTrackerControl(TopologyTracker filter) {
        initComponents();
        freezeLearningToggleButton.setSelected(!filter.isLearningEnabled());
        showStatusToggleButton.setSelected(filter.isShowStatus());
        showRawInputToggleButton.setSelected(!filter.isMapEventsToLearnedTopologyEnabled());
        this.filter=filter;
        pack();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetButton = new javax.swing.JButton();
        freezeLearningToggleButton = new javax.swing.JToggleButton();
        showStatusToggleButton = new javax.swing.JToggleButton();
        showRawInputToggleButton = new javax.swing.JToggleButton();

        setTitle("Reset filter");

        resetButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetButton.setText("Randomize topology");
        resetButton.setAlignmentX(0.5F);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        freezeLearningToggleButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        freezeLearningToggleButton.setText("Freeze learning");
        freezeLearningToggleButton.setAlignmentX(0.5F);
        freezeLearningToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freezeLearningToggleButtonActionPerformed(evt);
            }
        });

        showStatusToggleButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showStatusToggleButton.setText("Show status");
        showStatusToggleButton.setAlignmentX(0.5F);
        showStatusToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showStatusToggleButtonActionPerformed(evt);
            }
        });

        showRawInputToggleButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showRawInputToggleButton.setText("Show raw input");
        showRawInputToggleButton.setAlignmentX(0.5F);
        showRawInputToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRawInputToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(freezeLearningToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(showStatusToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(showRawInputToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(resetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(freezeLearningToggleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showStatusToggleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showRawInputToggleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
    if(filter!=null) filter.resetFilter();
}//GEN-LAST:event_resetButtonActionPerformed

private void freezeLearningToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freezeLearningToggleButtonActionPerformed
    if(filter!=null) 
        filter.setLearningEnabled(!freezeLearningToggleButton.isSelected());
}//GEN-LAST:event_freezeLearningToggleButtonActionPerformed

private void showStatusToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showStatusToggleButtonActionPerformed
    if(filter!=null) filter.setShowStatus(showStatusToggleButton.isSelected());
}//GEN-LAST:event_showStatusToggleButtonActionPerformed

private void showRawInputToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRawInputToggleButtonActionPerformed
    if(filter!=null) filter.setMapEventsToLearnedTopologyEnabled(!showRawInputToggleButton.isSelected());
}//GEN-LAST:event_showRawInputToggleButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton freezeLearningToggleButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JToggleButton showRawInputToggleButton;
    private javax.swing.JToggleButton showStatusToggleButton;
    // End of variables declaration//GEN-END:variables

}
