/*
 * CochleaAMS1bControlPanel.java
 *
 * Created on October 24, 2008, 5:39 PM
 */

package ch.unizh.ini.caviar.chip.cochlea;

import ch.unizh.ini.caviar.biasgen.BiasgenPanel;

/**
 * The custom control panel for CochleaAMS1b which includes IPots, VPots, local IPots, scanner, and digital control.
 * @author  tobi
 */
public class CochleaAMS1bControlPanel extends javax.swing.JPanel {
    
    CochleaAMS1b chip;
    CochleaAMS1b.Biasgen biasgen;
    
    /** Creates new form CochleaAMS1bControlPanel */
    public CochleaAMS1bControlPanel(CochleaAMS1b chip) {
        this.chip=chip;
        biasgen=(CochleaAMS1b.Biasgen)chip.getBiasgen();
        initComponents();
        biasgen.setPotArray(biasgen.ipots);
        onchipBiasgenPanel.add(new BiasgenPanel(biasgen,chip.getAeViewer().getBiasgenFrame())); // TODO fix panel contructor to not need parent
        biasgen.setPotArray(biasgen.vpots);
        offchipDACPanel.add(new BiasgenPanel(biasgen,chip.getAeViewer().getBiasgenFrame()));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        onchipBiasgenPanel = new javax.swing.JPanel();
        offchipDACPanel = new javax.swing.JPanel();
        configPanel = new javax.swing.JPanel();
        scannerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        onchipBiasgenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("On-chip biases"));
        onchipBiasgenPanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("on-chip biases", onchipBiasgenPanel);

        offchipDACPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Off-chip DAC biases"));
        offchipDACPanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("off-chip biases", offchipDACPanel);

        configPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuration"));
        configPanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("config", configPanel);

        scannerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Scanner control"));
        scannerPanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("scanner", scannerPanel);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel configPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel offchipDACPanel;
    private javax.swing.JPanel onchipBiasgenPanel;
    private javax.swing.JPanel scannerPanel;
    // End of variables declaration//GEN-END:variables

}
