/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClockApplet.java
 *
 * Created on Sep 16, 2009, 11:59:07 AM
 */

package net.sf.jaer.jaerappletviewer;

import java.awt.Graphics;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JApplet;
import javax.swing.JFrame;

/**
 * Shows clock and date as a applet, for possible use in INI foyer kiosk display instead of javascript clocks, which tend
 * to lose their synchronization.
 * @author tobi
 */
public class ClockApplet extends javax.swing.JApplet {
    private SimpleDateFormat timeFormat=new SimpleDateFormat("H:m:ss");
    private SimpleDateFormat dateFormat=new SimpleDateFormat("d MMM yyyy");
    /** Initializes the applet ClockApplet */
    @Override
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    @Override
    public void start() {
        super.start();
        repaint();
    }

    @Override
    public void stop() {
        super.stop();
        setVisible(false);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        Date date=new Date();
        timeLabel.setText(timeFormat.format(date));
        dateLabel.setText(dateFormat.format(date));
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {

        }
        repaint();
    }


        /**
     * For testing in JFrame
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JApplet applet = new ClockApplet();
        JFrame frame = new ActivityMonitorTest(applet);
        applet.init();
        applet.start();
        frame.setVisible(true);
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        timeLabel.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("time");
        getContentPane().add(timeLabel);

        dateLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("date");
        getContentPane().add(dateLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

}
