/*
 * Copyright (C) 2022 tobid.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package org.ine.telluride.jaer.tell2022;

import java.awt.event.KeyEvent;
import java.util.logging.Logger;

/**
 *
 * @author tobid
 */
public class GoingFishingFishingRodControlFrame extends javax.swing.JFrame {

    static Logger log = Logger.getLogger("GoingFishing");

    private long lastTimeMs = 0;
    private boolean recording = false;
    RodSequence rodSequence = new RodSequence(0);

    /**
     * Creates new form GoingFishingFishingRodControlFrame
     */
    public GoingFishingFishingRodControlFrame() {
        initComponents();
        buttonGroup1.add(fishingHoleButton0);
        buttonGroup1.add(fishingHoleButton1);
        fishingHoleButton0.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        recordToggleButton = new javax.swing.JToggleButton();
        rodControlPanel = new javax.swing.JPanel();
        helpText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        fishingHoleButton0 = new javax.swing.JRadioButton();
        fishingHoleButton1 = new javax.swing.JRadioButton();
        clearButton = new javax.swing.JButton();

        setTitle("Going Fishing Rod Control");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        recordToggleButton.setText("Record (r)");
        recordToggleButton.setToolTipText("Toggle recording of fishing rod movement");
        recordToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordToggleButtonActionPerformed(evt);
            }
        });

        rodControlPanel.setBackground(new java.awt.Color(102, 204, 255));
        rodControlPanel.setBorder(new javax.swing.border.MatteBorder(null));
        rodControlPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rodControlPanelMouseDragged(evt);
            }
        });
        rodControlPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rodControlPanelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rodControlPanelKeyTyped(evt);
            }
        });

        helpText.setEditable(false);
        helpText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        helpText.setText("Press left mouse button and drag to control rod");
        helpText.setFocusable(false);

        javax.swing.GroupLayout rodControlPanelLayout = new javax.swing.GroupLayout(rodControlPanel);
        rodControlPanel.setLayout(rodControlPanelLayout);
        rodControlPanelLayout.setHorizontalGroup(
            rodControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rodControlPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(helpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        rodControlPanelLayout.setVerticalGroup(
            rodControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rodControlPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(helpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        fishingHoleButton0.setText("Fishing hole 0");

        fishingHoleButton1.setText("Fishing hole 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fishingHoleButton0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fishingHoleButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fishingHoleButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fishingHoleButton1))
                .addContainerGap())
        );

        clearButton.setText("Clear all");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rodControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recordToggleButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(rodControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recordToggleButton)
                            .addComponent(clearButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rodControlPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rodControlPanelMouseDragged
        // first drag movement of mouse starts the sequencq
        requestFocusInWindow(); // to get key listeners to work
        int thetaDeg = (int) (Math.floor(180f * (float) evt.getX() / rodControlPanel.getWidth()));
        int zDeg = (int) (Math.floor(180f * (float) (rodControlPanel.getHeight() - evt.getY()) / rodControlPanel.getHeight()));
        final long currentTimeMillis = System.currentTimeMillis();
        final long delayToNextMs = lastTimeMs == 0 ? 0 : currentTimeMillis - lastTimeMs;

        // first step has zero delay
        RodPosition rodPosition = new RodPosition(delayToNextMs, thetaDeg, zDeg);
        if (recording) {
            rodSequence.add(rodPosition);
        }
        lastTimeMs = currentTimeMillis;
        firePropertyChange(GoingFishing.EVENT_ROD_POSITION, null, rodPosition);
    }//GEN-LAST:event_rodControlPanelMouseDragged

    private void rodControlPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rodControlPanelKeyTyped
        toggleRecording(evt);
    }//GEN-LAST:event_rodControlPanelKeyTyped


    private void recordToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordToggleButtonActionPerformed
        toggleRecording();
    }//GEN-LAST:event_recordToggleButtonActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        toggleRecording(evt);
    }//GEN-LAST:event_formKeyTyped

    private void rodControlPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rodControlPanelKeyPressed
       toggleRecording(evt);
    }//GEN-LAST:event_rodControlPanelKeyPressed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        firePropertyChange(GoingFishing.EVENT_CLEAR_SEQUENCES, null, null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void toggleRecording(KeyEvent evt) {
        if (evt.getKeyChar() == 'r') {
            recordToggleButton.setEnabled(!recordToggleButton.isEnabled());
            toggleRecording();
        }
    }

    private void toggleRecording() {
        recording = !recording;
        if (recording) {
            lastTimeMs = 0;
            int seq=fishingHoleButton0.isSelected()?0:1;
            RodSequence rodSequence=new RodSequence(seq);
            log.info("recording sequence "+seq);
        } else {
            firePropertyChange(GoingFishing.EVENT_ROD_SEQUENCE, null, rodSequence);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoingFishingFishingRodControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoingFishingFishingRodControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoingFishingFishingRodControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoingFishingFishingRodControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GoingFishingFishingRodControlFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private javax.swing.JRadioButton fishingHoleButton0;
    private javax.swing.JRadioButton fishingHoleButton1;
    private javax.swing.JTextField helpText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton recordToggleButton;
    private javax.swing.JPanel rodControlPanel;
    // End of variables declaration//GEN-END:variables

}
